#!/usr/bin/env bash

LLM_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$LLM_HOME/config/config.sh"

case "$1" in

    help)
        echo "Ran: llm help"
        source $LLM_HOME/scripts/help.sh
        ;;

    config)
        case "$2" in

            show)
                source $LLM_HOME/scripts/configshow.sh
                ;;

            edit)
                source $LLM_HOME/scripts/configedit.sh
                ;;

            "")
                echo "Option not specified; usage: llm config [show|edit]"
                ;;

            *)
                echo "Unknown config option: $2"
                echo "Usage: llm config [show|edit]"
                ;;

        esac
        ;;

    launch)
        case "$2" in

            "")
                "$LLM_HOME/scripts/launchdefault.sh"
                ;;

                default)
                    "$LLM_HOME/scripts/launchdefault.sh"
                ;;

            select)
                source $LLM_HOME/scripts/launchselect.sh
                ;;

            *)
                ;;

        esac
        ;;

    health)
        source $LLM_HOME/scripts/health.sh
        ;;

    "")
        echo "Usage: llm {help|config|launch|health}"
        ;;

    *)
        echo "Unknown command: $1"
        echo "Run 'llm help' for usage."
        ;;

esac
